services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      # Map the local src folder to the container's src folder
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env